name: Actualizar Eventos JSON

on:
  schedule:
    - cron: '*/15 * * * *' # Se ejecuta cada 15 minutos
  workflow_dispatch: # Permite ejecutarlo manualmente para probar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar Scraper
        run: python scraper.py

      - name: Guardar cambios en el JSON
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add eventos.json
          git commit -m "Actualización automática de eventos" || exit 0
          git push
